app:
  app_id: mapa_comida-backend
mongo:
  host: localhost
  port: 27017
  database: mapa-comida
  collection: users
  collection_places: places
  collection_spaces: spaces
  authentication:
  user:
  pass:
SECRET-KEY: xxx
logging:
  version: 1
  formatters:
    default:
      format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
  handlers:
    wsgi:
      class: logging.StreamHandler
      stream: ext://flask.logging.wsgi_errors_stream
      formatter: default
  root:
    level: INFO
    habdlers: [wsgi]